/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_PROTO_FILES_TEST_PB_H_INCLUDED
#define PB_PROTO_FILES_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DeviceSettings {
    pb_callback_t deviceid;
} DeviceSettings;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceSettings_init_default              {{{NULL}, NULL}}
#define DeviceSettings_init_zero                 {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceSettings_deviceid_tag              1

/* Struct field encoding specification for nanopb */
#define DeviceSettings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   deviceid,          1)
#define DeviceSettings_CALLBACK pb_default_field_callback
#define DeviceSettings_DEFAULT NULL

extern const pb_msgdesc_t DeviceSettings_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceSettings_fields &DeviceSettings_msg

/* Maximum encoded size of messages (where known) */
/* DeviceSettings_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
