/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include <settings.pb.h>
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MQTTTopics, MQTTTopics, AUTO)


PB_BIND(MQTTKeepAlive, MQTTKeepAlive, AUTO)


PB_BIND(MQTTCleanSession, MQTTCleanSession, AUTO)


PB_BIND(MQTTConfig, MQTTConfig, AUTO)


PB_BIND(SoftAPConfig, SoftAPConfig, AUTO)


PB_BIND(MDNSConfig, MDNSConfig, AUTO)


PB_BIND(DNSConfig, DNSConfig, AUTO)


PB_BIND(DHCPConfig, DHCPConfig, AUTO)


PB_BIND(NTPConfig, NTPConfig, AUTO)


PB_BIND(APConfig, APConfig, AUTO)


PB_BIND(WiFiConfig, WiFiConfig, AUTO)


PB_BIND(Settings, Settings, 2)




